#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libgit2-soname27
Version  : 0.27.8
Release  : 2
URL      : https://github.com/libgit2/libgit2/archive/v0.27.8.tar.gz
Source0  : https://github.com/libgit2/libgit2/archive/v0.27.8.tar.gz
Summary  : The git library, take 2
Group    : Development/Tools
License  : CC0-1.0 GPL-2.0 MIT
Requires: compat-libgit2-soname27-lib = %{version}-%{release}
Requires: compat-libgit2-soname27-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : libssh2-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libcurl)
BuildRequires : python-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : zlib-dev

%description
libgit2 examples
================
These examples are a mixture of basic emulation of core Git command line
functions and simple snippets demonstrating libgit2 API usage (for use
with Docurium).  As a whole, they are not vetted carefully for bugs, error
handling, and cross-platform compatibility in the same manner as the rest
of the code in libgit2, so copy with caution.

%package dev
Summary: dev components for the compat-libgit2-soname27 package.
Group: Development
Requires: compat-libgit2-soname27-lib = %{version}-%{release}
Provides: compat-libgit2-soname27-devel = %{version}-%{release}

%description dev
dev components for the compat-libgit2-soname27 package.


%package lib
Summary: lib components for the compat-libgit2-soname27 package.
Group: Libraries
Requires: compat-libgit2-soname27-license = %{version}-%{release}

%description lib
lib components for the compat-libgit2-soname27 package.


%package license
Summary: license components for the compat-libgit2-soname27 package.
Group: Default

%description license
license components for the compat-libgit2-soname27 package.


%prep
%setup -q -n libgit2-0.27.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550430872
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1550430872
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libgit2-soname27
cp COPYING %{buildroot}/usr/share/package-licenses/compat-libgit2-soname27/COPYING
cp deps/http-parser/LICENSE-MIT %{buildroot}/usr/share/package-licenses/compat-libgit2-soname27/deps_http-parser_LICENSE-MIT
cp examples/COPYING %{buildroot}/usr/share/package-licenses/compat-libgit2-soname27/examples_COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/git2.h
%exclude /usr/include/git2/annotated_commit.h
%exclude /usr/include/git2/attr.h
%exclude /usr/include/git2/blame.h
%exclude /usr/include/git2/blob.h
%exclude /usr/include/git2/branch.h
%exclude /usr/include/git2/buffer.h
%exclude /usr/include/git2/checkout.h
%exclude /usr/include/git2/cherrypick.h
%exclude /usr/include/git2/clone.h
%exclude /usr/include/git2/commit.h
%exclude /usr/include/git2/common.h
%exclude /usr/include/git2/config.h
%exclude /usr/include/git2/cred_helpers.h
%exclude /usr/include/git2/describe.h
%exclude /usr/include/git2/diff.h
%exclude /usr/include/git2/errors.h
%exclude /usr/include/git2/filter.h
%exclude /usr/include/git2/global.h
%exclude /usr/include/git2/graph.h
%exclude /usr/include/git2/ignore.h
%exclude /usr/include/git2/index.h
%exclude /usr/include/git2/indexer.h
%exclude /usr/include/git2/inttypes.h
%exclude /usr/include/git2/merge.h
%exclude /usr/include/git2/message.h
%exclude /usr/include/git2/net.h
%exclude /usr/include/git2/notes.h
%exclude /usr/include/git2/object.h
%exclude /usr/include/git2/odb.h
%exclude /usr/include/git2/odb_backend.h
%exclude /usr/include/git2/oid.h
%exclude /usr/include/git2/oidarray.h
%exclude /usr/include/git2/pack.h
%exclude /usr/include/git2/patch.h
%exclude /usr/include/git2/pathspec.h
%exclude /usr/include/git2/proxy.h
%exclude /usr/include/git2/rebase.h
%exclude /usr/include/git2/refdb.h
%exclude /usr/include/git2/reflog.h
%exclude /usr/include/git2/refs.h
%exclude /usr/include/git2/refspec.h
%exclude /usr/include/git2/remote.h
%exclude /usr/include/git2/repository.h
%exclude /usr/include/git2/reset.h
%exclude /usr/include/git2/revert.h
%exclude /usr/include/git2/revparse.h
%exclude /usr/include/git2/revwalk.h
%exclude /usr/include/git2/signature.h
%exclude /usr/include/git2/stash.h
%exclude /usr/include/git2/status.h
%exclude /usr/include/git2/stdint.h
%exclude /usr/include/git2/strarray.h
%exclude /usr/include/git2/submodule.h
%exclude /usr/include/git2/sys/commit.h
%exclude /usr/include/git2/sys/config.h
%exclude /usr/include/git2/sys/diff.h
%exclude /usr/include/git2/sys/filter.h
%exclude /usr/include/git2/sys/hashsig.h
%exclude /usr/include/git2/sys/index.h
%exclude /usr/include/git2/sys/mempack.h
%exclude /usr/include/git2/sys/merge.h
%exclude /usr/include/git2/sys/odb_backend.h
%exclude /usr/include/git2/sys/openssl.h
%exclude /usr/include/git2/sys/refdb_backend.h
%exclude /usr/include/git2/sys/reflog.h
%exclude /usr/include/git2/sys/refs.h
%exclude /usr/include/git2/sys/repository.h
%exclude /usr/include/git2/sys/stream.h
%exclude /usr/include/git2/sys/time.h
%exclude /usr/include/git2/sys/transport.h
%exclude /usr/include/git2/tag.h
%exclude /usr/include/git2/trace.h
%exclude /usr/include/git2/transaction.h
%exclude /usr/include/git2/transport.h
%exclude /usr/include/git2/tree.h
%exclude /usr/include/git2/types.h
%exclude /usr/include/git2/version.h
%exclude /usr/include/git2/worktree.h
%exclude /usr/lib64/libgit2.so
%exclude /usr/lib64/pkgconfig/libgit2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgit2.so.0.27.8
/usr/lib64/libgit2.so.27

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/compat-libgit2-soname27/COPYING
%exclude /usr/share/package-licenses/compat-libgit2-soname27/deps_http-parser_LICENSE-MIT
%exclude /usr/share/package-licenses/compat-libgit2-soname27/examples_COPYING
